CREATE TABLE `healthInsuranceClaims` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`policyId` int NOT NULL,
	`claimNumber` varchar(100) NOT NULL,
	`claimAmount` int NOT NULL,
	`hospitalName` varchar(255),
	`treatmentType` varchar(100),
	`admissionDate` timestamp,
	`dischargeDate` timestamp,
	`status` enum('submitted','under-review','approved','rejected','paid') NOT NULL DEFAULT 'submitted',
	`documentUrls` text,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`approvedAt` timestamp,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `healthInsuranceClaims_id` PRIMARY KEY(`id`),
	CONSTRAINT `healthInsuranceClaims_claimNumber_unique` UNIQUE(`claimNumber`)
);
--> statement-breakpoint
CREATE TABLE `healthInsurancePolicies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`policyNumber` varchar(100) NOT NULL,
	`providerName` varchar(255) NOT NULL,
	`sumInsured` int NOT NULL,
	`premiumAmount` int NOT NULL,
	`premiumFrequency` enum('monthly','quarterly','half-yearly','yearly') NOT NULL DEFAULT 'yearly',
	`coverageType` enum('individual','family','senior') NOT NULL DEFAULT 'individual',
	`familyMembers` int NOT NULL DEFAULT 1,
	`startDate` timestamp NOT NULL,
	`renewalDate` timestamp NOT NULL,
	`status` enum('active','inactive','lapsed','expired') NOT NULL DEFAULT 'active',
	`nextPremiumDueDate` timestamp,
	`lastPremiumPaidDate` timestamp,
	`networkHospitals` int DEFAULT 0,
	`cashlessLimit` int DEFAULT 0,
	`waitingPeriod` int DEFAULT 30,
	`documentUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `healthInsurancePolicies_id` PRIMARY KEY(`id`),
	CONSTRAINT `healthInsurancePolicies_policyNumber_unique` UNIQUE(`policyNumber`)
);
